"""
File Overview: Data Transfer Object (DTO) for analytical alerts generated by the system.

All Functions/Classes:
- alert_dto: Pydantic model for alert metadata. Take event data and send validated DTO.

Endpoints/APIs: None

Database Tables: None
"""
from datetime import datetime

from typing import Dict, Any
from shared.application.dto.base_dto import base_dto

class alert_dto(base_dto):
    event_type: str
    symbol: str
    payload: Dict[str, Any]
    fired_at: datetime
